import {
  faCartShopping,
  faMagnifyingGlass,
  faStar,
  faCircleCheck,
  faCircleXmark,
  faGauge,
  faCaretRight,
  faPeopleGroup,
  faBook,
  faBookBookmark,
  faFolderPlus,
  faBookAtlas,
  faXmark,
  faUpload,
  faUserLarge,
  faClockRotateLeft,
  faFileLines,
} from "@fortawesome/free-solid-svg-icons";
import {
  faFacebook,
  faTwitter,
  faInstagram,
} from "@fortawesome/free-brands-svg-icons";
import { faCircleUser } from "@fortawesome/free-regular-svg-icons";
const icon = {
  faCartShopping,
  faMagnifyingGlass,
  faStar,
  faCaretRight,
  faFacebook,
  faGauge,
  faTwitter,
  faInstagram,
  faCircleUser,
  faCircleCheck,
  faCircleXmark,
  faPeopleGroup,
  faBook,
  faBookBookmark,
  faFolderPlus,
  faBookAtlas,
  faXmark,
  faUpload,
  faUserLarge,
  faClockRotateLeft,
  faFileLines,
};

export default icon;
